baseurl = "/"
languageCode = "en-us"
title = "Scalatra"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
uglyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[permalinks]
  news = "/:year/:month/:day/:filename.html"



[params]
	# General information
	# author = "Scalatra Team"
	description = "Documentation and how-to guides for the Scalatra microframework."
	copyright = "Scalatra Team"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/scalatra/scalatra"

	# version = "2.5.0"
	logo = "images/logo.png"
	favicon = ""


	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "/stylesheets/highlight/highlight.css"

	[params.palette]
    	primary = "teal"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "scalatra"
	github  = "scalatra/scalatra"
	email   = ""


[[menu.main]]
	name   = "Getting started"
	url    = "/getting-started/"
	weight = 10

[[menu.main]]
	name   = "Guides"
	url    = "/2.5/guides/"
	weight = 20

[[menu.main]]
	name   = "Community"
	url    = "/community/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
